{"num_games": 100, "student_agent_wins": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], "random_agent_wins": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "student_agent_win_count": 100, "random_agent_win_count": 0, "student_agent_win_percentage": 1.0, "random_agent_win_percentage": 0.0, "student_agent_time_taken": 0.00686934232711792, "random_agent_time_taken": 0.002786550521850586, "run_info": [{"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0016756057739257812, "random_agent_time": 0.0017254352569580078, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 62, "random_agent_score": 2, "student_agent_time": 0.0063931941986083984, "random_agent_time": 0.0026493072509765625, "board_size": 8, "swap_players": false, "run_out": "[(4, 5), (5, 6), (5, 4)]\n[(5, 2), (7, 2)]\n[(5, 4), (5, 2)]\n[(6, 4), (5, 3)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 2] to [5 3] and put barrier at 1, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 97, "random_agent_score": 1, "student_agent_time": 0.005908489227294922, "random_agent_time": 0.0025718212127685547, "board_size": 10, "swap_players": false, "run_out": "[(1, 4), (2, 5), (3, 4), (2, 3)]\n[(1, 3), (2, 4), (3, 3)]\n[(0, 4), (1, 5), (1, 3)]\n[(0, 3), (1, 4)]\n[(0, 6), (1, 7), (1, 5)]\n[(0, 5), (1, 6)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.01058197021484375, "random_agent_time": 0.0033452510833740234, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 48, "random_agent_score": 1, "student_agent_time": 0.0015535354614257812, "random_agent_time": 0.0013585090637207031, "board_size": 7, "swap_players": true, "run_out": "[(2, 4), (4, 4), (3, 3)]\n[(3, 2)]\n"}, {"student_agent_score": 48, "random_agent_score": 1, "student_agent_time": 0.0016913414001464844, "random_agent_time": 0.0010597705841064453, "board_size": 7, "swap_players": true, "run_out": "[(2, 4), (4, 4), (3, 3)]\n[(3, 2)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.006444454193115234, "random_agent_time": 0.002012014389038086, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 62, "random_agent_score": 2, "student_agent_time": 0.008084774017333984, "random_agent_time": 0.003966093063354492, "board_size": 8, "swap_players": false, "run_out": "[(4, 5), (5, 6), (5, 4)]\n[(5, 2), (7, 2)]\n[(5, 4), (5, 2)]\n[(6, 4), (5, 3)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 2] to [5 3] and put barrier at 1, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0012676715850830078, "random_agent_time": 0.0011670589447021484, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.006396770477294922, "random_agent_time": 0.001977205276489258, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.011458396911621094, "random_agent_time": 0.002943754196166992, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0020542144775390625, "random_agent_time": 0.001500844955444336, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008419513702392578, "random_agent_time": 0.0021855831146240234, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 27, "random_agent_score": 4, "student_agent_time": 0.010618448257446289, "random_agent_time": 0.007659435272216797, "board_size": 6, "swap_players": false, "run_out": "[(2, 3), (3, 4), (3, 2)]\n[(2, 0), (3, 1)]\n[(2, 1), (3, 2)]\n[(2, 4), (3, 5)]\n[(2, 5), (1, 4)]\n[(2, 5), (4, 5)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 4] to [2 5] and put barrier at 2, with max steps = 3\n\nExecute Random Walk!\n[(4, 5), (4, 3)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 3] to [4 3] and put barrier at 1, with max steps = 3\n\nExecute Random Walk!\n[(4, 5)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 2] to [1 5] and put barrier at 2, with max steps = 3\n\nExecute Random Walk!\n[(3, 5), (5, 5)]\n[(5, 4), (5, 2)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 5] to [4 4] and put barrier at 3, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 97, "random_agent_score": 1, "student_agent_time": 0.007782697677612305, "random_agent_time": 0.0038623809814453125, "board_size": 10, "swap_players": false, "run_out": "[(1, 4), (2, 5), (3, 4), (2, 3)]\n[(1, 3), (2, 4), (3, 3)]\n[(0, 4), (1, 5), (1, 3)]\n[(0, 3), (1, 4)]\n[(0, 6), (1, 7), (1, 5)]\n[(0, 5), (1, 6)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.011907815933227539, "random_agent_time": 0.0029604434967041016, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 48, "random_agent_score": 1, "student_agent_time": 0.0025904178619384766, "random_agent_time": 0.0019500255584716797, "board_size": 7, "swap_players": true, "run_out": "[(2, 4), (4, 4), (3, 3)]\n[(3, 2)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0013837814331054688, "random_agent_time": 0.003773927688598633, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 48, "random_agent_score": 1, "student_agent_time": 0.002403736114501953, "random_agent_time": 0.002758026123046875, "board_size": 7, "swap_players": true, "run_out": "[(2, 4), (4, 4), (3, 3)]\n[(3, 2)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.010078191757202148, "random_agent_time": 0.004120826721191406, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009423017501831055, "random_agent_time": 0.0037903785705566406, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.01123189926147461, "random_agent_time": 0.0029685497283935547, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008656740188598633, "random_agent_time": 0.002759695053100586, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0021181106567382812, "random_agent_time": 0.0015201568603515625, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008953094482421875, "random_agent_time": 0.0026197433471679688, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009099960327148438, "random_agent_time": 0.0019731521606445312, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0017447471618652344, "random_agent_time": 0.002404928207397461, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.011706352233886719, "random_agent_time": 0.0033218860626220703, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0018489360809326172, "random_agent_time": 0.0014622211456298828, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009844303131103516, "random_agent_time": 0.00462031364440918, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009424209594726562, "random_agent_time": 0.003581523895263672, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00966024398803711, "random_agent_time": 0.004379987716674805, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.005760669708251953, "random_agent_time": 0.0016515254974365234, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0016820430755615234, "random_agent_time": 0.002755403518676758, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.00825643539428711, "random_agent_time": 0.0028579235076904297, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0017316341400146484, "random_agent_time": 0.0023462772369384766, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008336305618286133, "random_agent_time": 0.0020627975463867188, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.010109186172485352, "random_agent_time": 0.0038225650787353516, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009509801864624023, "random_agent_time": 0.0027163028717041016, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.010319709777832031, "random_agent_time": 0.003461122512817383, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.008867740631103516, "random_agent_time": 0.0036215782165527344, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.006226062774658203, "random_agent_time": 0.0019009113311767578, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0034208297729492188, "random_agent_time": 0.002475738525390625, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.007317781448364258, "random_agent_time": 0.0024497509002685547, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.002043485641479492, "random_agent_time": 0.0015301704406738281, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0019142627716064453, "random_agent_time": 0.0016162395477294922, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.007683277130126953, "random_agent_time": 0.003746509552001953, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009531497955322266, "random_agent_time": 0.003817319869995117, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.007338762283325195, "random_agent_time": 0.0023093223571777344, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0016586780548095703, "random_agent_time": 0.0016570091247558594, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.007531166076660156, "random_agent_time": 0.0035593509674072266, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009352684020996094, "random_agent_time": 0.0025644302368164062, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.007071733474731445, "random_agent_time": 0.0021533966064453125, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0013785362243652344, "random_agent_time": 0.0014476776123046875, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0013756752014160156, "random_agent_time": 0.001135110855102539, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.010313034057617188, "random_agent_time": 0.0036950111389160156, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.010728120803833008, "random_agent_time": 0.002351045608520508, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.007993698120117188, "random_agent_time": 0.002794504165649414, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.010783672332763672, "random_agent_time": 0.004829883575439453, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.007538318634033203, "random_agent_time": 0.002276897430419922, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.006573200225830078, "random_agent_time": 0.0018177032470703125, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0029277801513671875, "random_agent_time": 0.0018036365509033203, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.001390218734741211, "random_agent_time": 0.00124359130859375, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.009137153625488281, "random_agent_time": 0.004812955856323242, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008151531219482422, "random_agent_time": 0.0028314590454101562, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00657200813293457, "random_agent_time": 0.0038022994995117188, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.003390789031982422, "random_agent_time": 0.0014722347259521484, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.00840139389038086, "random_agent_time": 0.002721548080444336, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.009663105010986328, "random_agent_time": 0.004437923431396484, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008540153503417969, "random_agent_time": 0.0027396678924560547, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00816965103149414, "random_agent_time": 0.004072666168212891, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.00887918472290039, "random_agent_time": 0.002386331558227539, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008700370788574219, "random_agent_time": 0.0022199153900146484, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.010040283203125, "random_agent_time": 0.0029184818267822266, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.002192258834838867, "random_agent_time": 0.0033757686614990234, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.009701251983642578, "random_agent_time": 0.004509449005126953, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.007935523986816406, "random_agent_time": 0.0033690929412841797, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008897542953491211, "random_agent_time": 0.0027158260345458984, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.002017974853515625, "random_agent_time": 0.0022644996643066406, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008640050888061523, "random_agent_time": 0.0028035640716552734, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0021643638610839844, "random_agent_time": 0.001560211181640625, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.00206756591796875, "random_agent_time": 0.0015001296997070312, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008557319641113281, "random_agent_time": 0.0022106170654296875, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.01069784164428711, "random_agent_time": 0.004066944122314453, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.007205486297607422, "random_agent_time": 0.002142190933227539, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0014977455139160156, "random_agent_time": 0.0012631416320800781, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.01058197021484375, "random_agent_time": 0.002771615982055664, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008366107940673828, "random_agent_time": 0.0024843215942382812, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.011579275131225586, "random_agent_time": 0.0037462711334228516, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.01078343391418457, "random_agent_time": 0.0035505294799804688, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.006125211715698242, "random_agent_time": 0.0018236637115478516, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.011090993881225586, "random_agent_time": 0.003154754638671875, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.010445833206176758, "random_agent_time": 0.004069805145263672, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.006715536117553711, "random_agent_time": 0.0023255348205566406, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 79, "random_agent_score": 2, "student_agent_time": 0.0019049644470214844, "random_agent_time": 0.0030748844146728516, "board_size": 9, "swap_players": true, "run_out": "[(4, 3), (5, 4)]\n[(4, 4), (6, 4), (5, 3)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.008799076080322266, "random_agent_time": 0.003278493881225586, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.008191823959350586, "random_agent_time": 0.0023462772369384766, "board_size": 11, "swap_players": false, "run_out": "[(8, 3), (9, 4), (10, 3), (9, 2)]\n[(8, 6), (9, 7), (10, 6)]\n[(6, 5), (8, 5), (7, 4)]\n[(6, 4)]\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.007070779800415039, "random_agent_time": 0.0025415420532226562, "board_size": 11, "swap_players": true, "run_out": "[(0, 10), (2, 10)]\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 310, in step\n    next_pos, dir = self.run_agent_step(cur_player, cur_pos, adv_pos)\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-vishvak-mark/world.py\", line 274, in run_agent_step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [3 3] and put barrier at 1, with max steps = 6\n\nExecute Random Walk!\n[(2, 9), (4, 9), (3, 8)]\n[(3, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00725865364074707, "random_agent_time": 0.004434823989868164, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.007727384567260742, "random_agent_time": 0.0034346580505371094, "board_size": 9, "swap_players": false, "run_out": "[(2, 4), (3, 5), (4, 4), (3, 3)]\n[(2, 3), (3, 4), (4, 3)]\n[(4, 4), (3, 3)]\n[(5, 5), (6, 6), (7, 5)]\n[(6, 7), (7, 6)]\n[(7, 6), (8, 7)]\n"}]}